## Read Datasets (csv,json,parquet)

In [1]:
import pandas as pd

In [2]:
import os

In [3]:
import numpy as np

# CSV File

In [9]:
csv_path1 = "C:\\Users\\sriharini\\Documents\\co-ecommerce.csv"

### Read Datasets

In [5]:
import pandas as pd

In [6]:
df_csv1 = pd.read_csv(csv_path1)

In [7]:
df_csv1

,uniq_id,product_name,manufacturer,price,number_available_in_stock,number_of_reviews,number_of_answered_questions,average_review_rating,amazon_category_and_sub_category,customers_who_bought_this_item_also_bought,description,product_information,product_description,items_customers_buy_after_viewing_this_item,customer_questions_and_answers,customer_reviews,sellers
0,eac7efa5dbd3d667f26eb3d3ab504464,Hornby 2014 Catalogue,Hornby,£3.42,5 new,15,1.0,4.9 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,http://www.amazon.co.uk/Hornby-R8150-Catalogue...,Product Description Hornby 2014 Catalogue Box ...,Technical Details Item Weight640 g Product Dim...,Product Description Hornby 2014 Catalogue Box ...,http://www.amazon.co.uk/Hornby-R8150-Catalogue...,Does this catalogue detail all the previous Ho...,Worth Buying For The Pictures Alone (As Ever) ...,"{""seller""=>[{""Seller_name_1""=>""Amazon.co.uk"", ..."
1,b17540ef7e86e461d37f3ae58b7b72ac,FunkyBuys® Large Christmas Holiday Express Fes...,FunkyBuys,£16.99,NaN,2,1.0,4.5 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,http://www.amazon.co.uk/Christmas-Holiday-Expr...,Size Name:Large FunkyBuys® Large Christmas Hol...,Technical Details Manufacturer recommended age...,Size Name:Large FunkyBuys® Large Christmas Hol...,http://www.amazon.co.uk/Christmas-Holiday-Expr...,can you turn off sounds // hi no you cant turn...,Four Stars // 4.0 // 18 Dec. 2015 // By\n \...,"{""seller""=>{""Seller_name_1""=>""UHD WHOLESALE"", ..."
2,348f344247b0c1a935b1223072ef9d8a,CLASSIC TOY TRAIN SET TRACK CARRIAGES LIGHT EN...,ccf,£9.99,2 new,17,2.0,3.9 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,http://www.amazon.co.uk/Classic-Train-Lights-B...,BIG CLASSIC TOY TRAIN SET TRACK CARRIAGE LIGHT...,Technical Details Manufacturer recommended age...,BIG CLASSIC TOY TRAIN SET TRACK CARRIAGE LIGHT...,http://www.amazon.co.uk/Train-With-Tracks-Batt...,What is the gauge of the track // Hi Paul.Trut...,**Highly Recommended!** // 5.0 // 26 May 2015 ...,"{""seller""=>[{""Seller_name_1""=>""DEAL-BOX"", ""Sel..."
3,e12b92dbb8eaee78b22965d2a9bbbd9f,HORNBY Coach R4410A BR Hawksworth Corridor 3rd,Hornby,£39.99,NaN,1,2.0,5.0 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,NaN,Hornby 00 Gauge BR Hawksworth 3rd Class W 2107...,Technical Details Item Weight259 g Product Dim...,Hornby 00 Gauge BR Hawksworth 3rd Class W 2107...,NaN,NaN,I love it // 5.0 // 22 July 2013 // By\n \n...,NaN
4,e33a9adeed5f36840ccc227db4682a36,Hornby 00 Gauge 0-4-0 Gildenlow Salt Co. Steam...,Hornby,£32.19,NaN,3,2.0,4.7 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,http://www.amazon.co.uk/Hornby-R6367-RailRoad-...,Product Description Hornby RailRoad 0-4-0 Gild...,Technical Details Item Weight159 g Product Dim...,Product Description Hornby RailRoad 0-4-0 Gild...,http://www.amazon.co.uk/Hornby-R2672-RailRoad-...,NaN,Birthday present // 5.0 // 14 April 2014 // By...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,44d6967f083825a5de36ad4865a65bcd,Batman 1966 TV Series Action Figures - The Rid...,Mattel,£22.95,5 new,3,3.0,5.0 out of 5 stars,Hobbies > Collectible Figures & Memorabilia > ...,http://www.amazon.co.uk/Batman-1966-Series-Act...,DC 66 Batman Classic TV Series 6 Inch Riddler ...,Technical Details Item Weight136 g Product Dim...,DC 66 Batman Classic TV Series 6 Inch Riddler ...,NaN,NaN,Realistic // 5.0 // 31 Mar. 2014 // By\n \n...,"{""seller""=>[{""Seller_name_1""=>""Star Action Fig..."
9996,08f0747b6fc6687215ffb994c3a6fb32,"Star Wars Costume, Kids Stormtrooper Costume S...",Star Wars,£39.99,NaN,1,3.0,4.0 out of 5 stars,Characters & Brands > Star Wars > Toys,http://www.amazon.co.uk/Storm-Trooper-Costume-...,NaN,Technical Details Additional Information AS...,NaN,http://www.amazon.co.uk/Storm-Trooper-Costume-...,NaN,... what I see my grandson us going to have fu...,NaN
9997,bf6cc073f8f24e6e338190fa16f6ee9d,Defiance Lawkeeper Metal Badge Prop Replica,Olde Scotland Yard Ltd.,£43.99,3 new,1,3.0,5.0 out of 5 stars,Novelty & Special Use > Novelty > Accessories ...,NaN,*Includes 1x Badge with holder and chain *High...,Technical Details Item Weight159 g Product Dim...,*Includes 1x Badge with holder and chain *High...,http://www.amazon.co.uk/Olde-Scotland-Yard-Ltd...,NaN,Five Stars // 5.0 // 18 Dec. 2015 // By\n \...,"{""seller""=>[{""Seller_name_1""=>""YUK"", ""Seller_p..."
9998,cd783d0b8b44e631b9788b203eaaefae,Justice League of America Series 3 Green Lante...,DC Comics,£49.81,3 new,1,3.0,5.0 out of 5 stars,Hobbies > Collectible Figures & Memorabilia > ...,NaN,Designed by Ed BenesIt's here - the third seri...,Technical Details Item Weight181 g Product Dim...,Designed by Ed BenesIt's here - the third seri...,NaN,NaN,The best sculpt in a while // 5.0 // 13 May 20...,"{""seller""=>[{""Seller_name_1""=>""Smaller World F..."
9999,94d18e86e504bee1e392df7e5738b18a,Star Wars 1/72 Y-Wing Starfighter,Bandai,£21.20,31 new,11,3.0,4.5 out of 5 stars,Characters & Brands > Star Wars > Toys,http://www.amazon.co.uk/Bandai-Star-Wars-Fight...,NaN,Technical Details Item Weight299 g Product Dim...,NaN,NaN,NaN,Gold leader // 5.0 // 31 Aug. 2015 // By\n ...,NaN

In [2]:
csv_path2 = "C:\\Users\\sriharini\\Documents\\emails.csv"
csv_path3 = "C:\\Users\\sriharini\\Documents\\us-counties.csv"

In [9]:
df_csv2 = pd.read_csv(csv_path2)
df_csv3 = pd.read_csv(csv_path3)

In [10]:
df_csv2

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 1,0,0,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 2,8,13,24,6,6,2,102,1,27,...,0,0,0,0,0,0,0,1,0,0
2,Email 3,0,0,1,0,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Email 4,0,5,22,0,5,1,51,2,10,...,0,0,0,0,0,0,0,0,0,0
4,Email 5,7,6,17,1,5,2,57,0,9,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5167,Email 5168,2,2,2,3,0,0,32,0,0,...,0,0,0,0,0,0,0,0,0,0
5168,Email 5169,35,27,11,2,6,5,151,4,3,...,0,0,0,0,0,0,0,1,0,0
5169,Email 5170,0,0,1,1,0,0,11,0,0,...,0,0,0,0,0,0,0,0,0,1
5170,Email 5171,2,7,1,0,2,1,28,2,0,...,0,0,0,0,0,0,0,1,0,1
5171,Email 5172,22,24,5,1,6,5,148,8,2,...,0,0,0,0,0,0,0,0,0,0

In [11]:
df_csv3

               date      county       state     fips  cases  deaths
0        2020-01-21   Snohomish  Washington  53061.0      1     0.0
1        2020-01-22   Snohomish  Washington  53061.0      1     0.0
2        2020-01-23   Snohomish  Washington  53061.0      1     0.0
3        2020-01-24        Cook    Illinois  17031.0      1     0.0
4        2020-01-24   Snohomish  Washington  53061.0      1     0.0
...             ...         ...         ...      ...    ...     ...
2502827  2022-05-13  Sweetwater     Wyoming  56037.0  11088   126.0
2502828  2022-05-13       Teton     Wyoming  56039.0  10074    16.0
2502829  2022-05-13       Uinta     Wyoming  56041.0   5643    39.0
2502830  2022-05-13    Washakie     Wyoming  56043.0   2358    44.0
2502831  2022-05-13      Weston     Wyoming  56045.0   1588    18.0

[2502832 rows x 6 columns]

# JSON file

In [12]:
import json

In [13]:
import pandas as pd

In [3]:
json_path1 = "C:\\Users\\sriharini\\Documents\\One Piece json.json"

In [15]:
with open(json_path1, "r") as f:
    raw_data1 = json.load(f)

In [16]:
df_json1 = pd.json_normalize(raw_data1)

In [17]:
df_json1

,Unnamed: 0,rank,trend,season,episode,name,start,total_votes,average_rating
0,0,"24,129",18,1,1,I'm Luffy! The Man Who Will Become the Pirate ...,1999,647,7.6
1,1,"29,290",11,1,2,"The Great Swordsman Appears! Pirate Hunter, Ro...",1999,473,7.8
2,2,"32,043",7,1,3,Morgan vs. Luffy! Who's This Beautiful Young G...,1999,428,7.7
3,3,"28,818",8,1,4,Luffy's Past! The Red-haired Shanks Appears!,1999,449,8.1
4,4,"37,113",4,1,5,"Fear, Mysterious Power! Pirate Clown Captain B...",1999,370,7.5
...,...,...,...,...,...,...,...,...,...
953,953,"41,448",26,1,954,Its Name is Enma! Oden's Meito!,2020,302,7.7
954,954,"35,342",44,1,955,&quot;A New Alliance?! Kaido's Army Gathers&quot;,2020,407,7.4
955,955,"33,715",75,1,956,Ticking Down to the Great Battle! The Straw Ha...,2020,353,8.2
956,956,"2,940",964,1,957,Big News! The Warlords Attack Incident,2021,"2,862",9.1
957,957,"14,751",-,1,958,&quot;The Legendary Battle! Garp and Roger&quot;,2021,746,9.4

In [4]:
json_path2 = "C:\\Users\\sriharini\\Documents\\schedules.json"

In [19]:
with open(json_path2, "r") as f:
    data2 = json.load(f)

In [20]:
df_json2 = pd.json_normalize(data2)

In [21]:
df_json2

,arrival,day,train_name,station_name,station_code,id,train_number,departure
0,None,1.0,Falaknuma Lingampalli MMTS,KACHEGUDA FALAKNUMA,FM,302214,47154,07:55:00
1,None,1.0,Thrissur Guruvayur Passenger,THRISUR,TCR,281458,56044,18:55:00
2,None,1.0,Porbandar Muzaffarpur Express,PORBANDAR,PBR,309335,19269,15:05:00
3,None,1.0,RAIPUR ITWARI PASS,RAIPUR JN,R,283774,58205,13:30:00
4,None,1.0,Gomoh-Asansol MEMU,GOMOH JN,GMO,319937,63542,07:20:00
...,...,...,...,...,...,...,...,...
417075,12:39:00,2.0,HOWRAH - JAYNAGAR Passenger,RAJANAGAR,RJA,424266,53041,12:39:00
417076,12:46:00,2.0,HOWRAH - JAYNAGAR Passenger,LALIT LAKSHMIPR,LLPR,424267,53041,12:47:00
417077,12:59:00,2.0,HOWRAH - JAYNAGAR Passenger,KHAJAULI,KJI,424268,53041,13:00:00
417078,13:09:00,2.0,HOWRAH - JAYNAGAR Passenger,KORAHIA,KRHA,424269,53041,13:10:00
417079,14:20:00,2.0,HOWRAH - JAYNAGAR Passenger,JAYNAGAR,JYG,424270,53041,None

In [5]:
json_path3 = "C:\\Users\\sriharini\\Documents\\file2.json"

In [23]:
with open(json_path3, "r") as f:
    data3 = json.load(f)

In [24]:
df_json3 = pd.json_normalize(data3)

In [25]:
df_json3

,results_found,results_start,results_shown,restaurants
0,1263908,21,20,"[{'restaurant': {'R': {'res_id': 16668008}, 'a..."
1,1263908,21,20,"[{'restaurant': {'R': {'res_id': 16668008}, 'a..."
2,1263908,21,20,"[{'restaurant': {'R': {'res_id': 16668008}, 'a..."
3,1263908,21,20,"[{'restaurant': {'R': {'res_id': 16668008}, 'a..."
4,1263908,21,20,"[{'restaurant': {'R': {'res_id': 16668008}, 'a..."
...,...,...,...,...
545,32,21,11,"[{'restaurant': {'R': {'res_id': 18433895}, 'a..."
546,17151,21,20,"[{'restaurant': {'R': {'res_id': 313256}, 'api..."
547,33,21,12,"[{'restaurant': {'R': {'res_id': 309672}, 'api..."
548,17151,21,20,"[{'restaurant': {'R': {'res_id': 313256}, 'api..."
549,17151,21,20,"[{'restaurant': {'R': {'res_id': 313256}, 'api..."

# Parquet file

In [26]:
pip install pyarrow

Requirement already satisfied: pyarrow in C:\Users\magiratchan\anaconda3\envs\Dataengg\Lib\site-packages (23.0.1)
Note: you may need to restart the kernel to use updated packages.

In [27]:
import pandas as pd

In [6]:
parquet_path = "C:\\Users\\sriharini\\Documents\\starships.parquet"

In [34]:
df_parquet = pd.read_parquet(parquet_path, engine="pyarrow")

In [35]:
df_parquet

,id,name,model,manufacturer,cost_in_credits,length,max_atmosphering_speed,crew,passengers,cargo_capacity,consumables,hyperdrive_rating,MGLT,starship_class,pilots,films
0,1,Millennium Falcon,YT-1300 light freighter,Corellian Engineering Corporation,1.000000e+05,34.75,1050.0,4.0,6.0,100000.0,2 months,0.50,75.0,Light freighter,"Han Solo, Chewbacca","A New Hope, The Empire Strikes Back, Return of..."
1,2,X-wing,T-65 X-wing starfighter,Incom Corporation,1.499990e+05,12.50,1050.0,1.0,0.0,110.0,1 week,1.00,100.0,Starfighter,Luke Skywalker,"A New Hope, The Empire Strikes Back, Return of..."
2,3,TIE Fighter,Twin Ion Engine/Ln Starfighter,Sienar Fleet Systems,7.500000e+04,8.99,1200.0,1.0,0.0,65.0,2 days,1.00,100.0,Starfighter,None,"A New Hope, The Empire Strikes Back, Return of..."
3,4,Star Destroyer,Imperial I-class Star Destroyer,Kuat Drive Yards,1.500000e+08,1600.00,975.0,47060.0,0.0,36000000.0,2 years,2.00,60.0,Capital ship,None,"A New Hope, The Empire Strikes Back, Return of..."
4,5,Slave 1,Firespray-31-class patrol and attack craft,Kuat Systems Engineering,NaN,21.50,1000.0,1.0,6.0,80000.0,1 month,3.00,70.0,Patrol craft,Boba Fett,"The Empire Strikes Back, Attack of the Clones,..."
5,6,A-wing,RZ-1 A-wing interceptor,Alliance Underground Engineering,1.750000e+05,9.60,1300.0,1.0,0.0,40.0,1 week,1.00,120.0,Interceptor,None,"Return of the Jedi, The Last Jedi"
6,7,B-wing,A/SF-01 B-wing starfighter,Slayn & Korpil,2.200000e+05,16.90,950.0,1.0,0.0,45.0,1 week,2.00,91.0,Assault starfighter,None,Return of the Jedi
7,8,Y-wing,BTL Y-wing starfighter,Koensayr Manufacturing,1.350000e+05,23.40,1000.0,2.0,0.0,110.0,1 week,1.00,80.0,Assault starfighter,None,"A New Hope, The Empire Strikes Back, Return of..."
8,9,Executor,Executor-class Star Dreadnought,"Kuat Drive Yards, Fondor Shipyards",1.143350e+09,19000.00,975.0,279144.0,38000.0,250000000.0,6 years,4.00,40.0,Star Dreadnought,Darth Vader,"The Empire Strikes Back, Return of the Jedi"
9,10,Rebel transport,GR-75 medium transport,"Gallofree Yards, Inc.",3.000000e+06,90.00,650.0,6.0,90.0,19000000.0,6 months,4.00,20.0,Medium transport,None,"The Empire Strikes Back, Return of the Jedi"
10,11,Naboo Royal Starship,J-type 327 Nubian,Theed Palace Space Vessel Engineering Corps,NaN,76.00,920.0,8.0,20.0,2000000.0,1 month,1.80,75.0,Yacht,Queen Amidala,The Phantom Menace
11,12,ARC-170,Aggressive ReConnaissance-170 starfighter,"Incom Corporation, Subpro Corporation",NaN,14.50,1000.0,3.0,0.0,110.0,5 days,1.00,100.0,Starfighter,None,Revenge of the Sith
12,13,Eta-2 Actis,Eta-2 Actis-class light interceptor,Kuat Systems Engineering,NaN,5.47,1500.0,1.0,0.0,60.0,2 days,1.00,85.0,Interceptor,"Anakin Skywalker, Obi-Wan Kenobi",Revenge of the Sith
13,14,Venator-class Star Destroyer,Venator-class,Kuat Drive Yards,NaN,1137.00,975.0,7400.0,2000.0,20000000.0,6 years,2.00,60.0,Capital ship,None,"Revenge of the Sith, The Clone Wars"
14,15,Naboo N-1 Starfighter,N-1,Theed Palace Space Vessel Engineering Corps,NaN,11.00,1100.0,1.0,0.0,65.0,3 days,1.00,100.0,Starfighter,Anakin Skywalker,"The Phantom Menace, Attack of the Clones"
15,16,Jedi Interceptor,Eta-2 Actis-class interceptor,Kuat Systems Engineering,NaN,5.47,1500.0,1.0,0.0,60.0,2 days,1.00,85.0,Interceptor,"Anakin Skywalker, Obi-Wan Kenobi",Revenge of the Sith
16,17,Sith Infiltrator,Scimitar,Republic Sienar Systems,NaN,26.50,1180.0,1.0,6.0,150000.0,1 month,1.50,80.0,Starfighter,Darth Maul,The Phantom Menace
17,18,V-wing,Alpha-3 Nimbus-class V-wing starfighter,Kuat Systems Engineering,NaN,7.90,1050.0,1.0,0.0,60.0,2 days,1.00,90.0,Starfighter,None,Revenge of the Sith
18,19,Delta-7 Aethersprite,Delta-7 Aethersprite-class light interceptor,Kuat Systems Engineering,NaN,8.00,1150.0,1.0,0.0,60.0,2 days,1.00,90.0,Interceptor,Obi-Wan Kenobi,Attack of the Clones
19,20,Imperial Shuttle,Lambda-class T-4a shuttle,Sienar Fleet Systems,NaN,20.00,850.0,6.0,20.0,80000.0,1 month,1.00,50.0,Shuttle,Emperor Palpatine,Return of the Jedi
20,21,Tantive IV,CR90 corvette,Corellian Engineering Corporation,3.500000e+06,150.00,950.0,165.0,30.0,3000000.0,1 year,2.00,60.0,Corvette,Leia Organa,"A New Hope, Revenge of the Sith"
21,22,Slave II,Firespray-31-class patrol and attack craft,Kuat Systems Engineering,NaN,21.50,1000.0,1.0,6.0,80000.0,1 month,3.00,70.0,Patrol craft,Boba Fett,"The Empire Strikes Back, Attack of the Clones,..."
22,23,TIE Bomber,TIE/sa bomber,Sienar Fleet Systems,NaN,7.80,850.0,1.0,0.0,40.0,2 days,1.00,60.0,Bomber,None,The Empire Strikes Back
23,24,Imperial Star Destroyer,Imperial I-class Star Destroyer,Kuat Drive Yards,1.500000e+08,1600.00,975.0,47060.0,0.0,36000000.0,2 years,2.00,60.0,Capital ship,None,"A New Hope, The Empire Strikes Back, Return of..."
24,25,Sith Speeder,FC-20 speeder bike,Razalon,NaN,2.00,180.0,1.0,0.0,10.0,1 day,NaN,NaN,Speeder,Darth Maul,The Phantom Menace
25,26,Speeder Bike,74-Z speeder bike,Aratech Repulsor Company,NaN,3.00,360.0,1.0,1.0,4.0,2 days,NaN,NaN,Speeder,None,Return of the Jedi
26,27,Solar Sailer,Punworcca 116-class interstellar sloop,Huppla Pasa Tisc Shipwrights Collective,NaN,15.20,NaN,3.0,11.0,180000.0,1 month,1.50,60.0,Sloop,Count Dooku,Attack of the Clones
27,28,Geonosian Starfighter,Nantex-class territorial defense starfighter,Huppla Pasa Tisc Shipwrights Collective,NaN,9.80,1200.0,1.0,0.0,30.0,2 days,1.00,100.0,Starfighter,None,Attack of the Clones
28,29,Hound's Tooth,YT-2000 light freighter,Corellian Engineering Corporation,NaN,20.00,850.0,6.0,10.0,500000.0,2 months,1.00,75.0,Light freighter,Bossk,The Clone Wars
29,30,Scimitar,Sith Infiltrator,Republic Sienar Systems,NaN,26.50,1180.0,1.0,6.0,150000.0,1 month,1.50,80.0,Starfighter,Darth Maul,The Phantom Menace
30,31,Tie Interceptor,TIE/in interceptor,Sienar Fleet Systems,NaN,9.60,1250.0,1.0,0.0,75.0,2 days,1.00,110.0,Starfighter,None,Return of the Jedi
31,32,Naboo Royal Cruiser,J-type diplomatic barge,Theed Palace Space Vessel Engineering Corps,NaN,115.00,920.0,8.0,50.0,500000.0,2 months,1.80,75.0,Yacht,Queen Amidala,Attack of the Clones
32,33,X-34 Landspeeder,X-34,SoroSuub Corporation,NaN,3.40,250.0,1.0,1.0,5.0,2 days,NaN,NaN,Landspeeder,Luke Skywalker,A New Hope
33,34,Snowspeeder,T-47 airspeeder,Incom Corporation,NaN,5.30,650.0,2.0,0.0,10.0,2 days,NaN,NaN,Airspeeder,Luke Skywalker,The Empire Strikes Back
34,35,The Ghost,VCX-100 light freighter,Corellian Engineering Corporation,NaN,43.90,1025.0,4.0,6.0,70000.0,2 months,1.00,70.0,Light freighter,Hera Syndulla,Star Wars Rebels
35,36,Phantom,VCX-series auxiliary starfighter,Corellian Engineering Corporation,NaN,14.10,1050.0,1.0,6.0,40000.0,1 month,1.00,90.0,Auxiliary starfighter,Ezra Bridger,Star Wars Rebels
36,37,Outrider,YT-2400 light freighter,Corellian Engineering Corporation,NaN,21.50,950.0,2.0,6.0,70000.0,2 months,0.75,70.0,Light freighter,Dash Rendar,Shadows of the Empire
37,38,Razor Crest,ST-70 Assault Ship,Kuat Drive Yards,NaN,24.00,1000.0,2.0,6.0,50000.0,1 month,1.00,75.0,Assault ship,Din Djarin,The Mandalorian
38,39,Naboo Yacht,J-type star skiff,Theed Palace Space Vessel Engineering Corps,NaN,29.20,920.0,8.0,30.0,300000.0,1 month,1.80,75.0,Yacht,Padmé Amidala,Revenge of the Sith
39,40,U-wing,UT-60D,Incom Corporation,NaN,24.20,950.0,4.0,8.0,40000.0,1 month,1.00,80.0,Transport,Cassian Andor,Rogue One
40,41,TIE Advanced x1,TIE Advanced x1,Sienar Fleet Systems,NaN,9.20,1200.0,1.0,0.0,75.0,2 days,1.00,105.0,Starfighter,Darth Vader,A New Hope
41,42,J-type 327 Nubian,J-type 327,Theed Palace Space Vessel Engineering Corps,NaN,76.00,920.0,8.0,20.0,2000000.0,1 month,1.80,75.0,Yacht,Queen Amidala,The Phantom Menace
42,43,Naboo Royal Starship,J-type 327 Nubian,Theed Palace Space Vessel Engineering Corps,NaN,76.00,920.0,8.0,20.0,2000000.0,1 month,1.80,75.0,Yacht,Queen Amidala,The Phantom Menace
43,44,Naboo N-1 Starfighter,N-1,Theed Palace Space Vessel Engineering Corps,NaN,11.00,1100.0,1.0,0.0,65.0,3 days,1.00,100.0,Starfighter,Anakin Skywalker,"The Phantom Menace, Attack of the Clones"
44,45,Sith Infiltrator,Scimitar,Republic Sienar Systems,NaN,26.50,1180.0,1.0,6.0,150000.0,1 month,1.50,80.0,Starfighter,Darth Maul,The Phantom Menace
45,46,Havoc Marauder,Omicron-class attack shuttle,Cygnus Spaceworks,NaN,22.30,1050.0,2.0,12.0,70000.0,1 month,1.00,70.0,Attack shuttle,Clone Force 99,The Bad Batch
46,47,Luthen's Ship,Fondor Haulcraft,Fondor Shipyards,NaN,34.80,1000.0,1.0,6.0,100000.0,1 month,1.00,80.0,Haulcraft,Luthen Rael,Andor
47,48,Tantive IV,CR90 corvette,Corellian Engineering Corporation,3.500000e+06,150.00,950.0,165.0,30.0,3000000.0,1 year,2.00,60.0,Corvette,Leia Organa,"A New Hope, Revenge of the Sith"
48,49,Millennium Falcon,YT-1300 light freighter,Corellian Engineering Corporation,1.000000e+05,34.75,1050.0,4.0,6.0,100000.0,2 months,0.50,75.0,Light freighter,"Han Solo, Chewbacca","A New Hope, The Empire Strikes Back, Return of..."
49,50,Jedi Starfighter,Delta-7 Aethersprite-class light interceptor,Kuat Systems Engineering,NaN,8.00,1150.0,1.0,0.0,60.0,2 days,1.00,90.0,Interceptor,Obi-Wan Kenobi,Attack of the Clones
50,51,Vulture Droid,Variable Geometry Self-Propelled Battle Droid,Haor Chall Engineering,NaN,3.50,1200.0,NaN,NaN,NaN,NaN,1.00,100.0,Starfighter,None,The Phantom Menace
51,52,Tri-Fighter,Droid Tri-Fighter,"Colla Designs, Phlac-Arphocc Automata Industries",NaN,5.40,1180.0,NaN,NaN,NaN,NaN,1.00,100.0,Starfighter,None,Revenge of the Sith
52,53,Hyena Bomber,Baktoid Armor Workshop,"Colla Designs, Phlac-Arphocc Automata Industries",NaN,14.90,1180.0,NaN,NaN,NaN,NaN,1.00,100.0,Starfighter,None,The Clone Wars
53,54,Droid Gunship,Heavy Missile Platform,Baktoid Fleet Ordnance,NaN,12.00,950.0,NaN,NaN,NaN,NaN,1.00,100.0,Gunship,None,The Clone Wars
54,55,Malevolence,Subjugator-class heavy cruiser,Free Dac Volunteers Engineering Corps,NaN,4845.00,975.0,216.0,0.0,14000000.0,6 years,1.50,60.0,Heavy cruiser,General Grievous,The Clone Wars
55,56,Invisible Hand,Providence-class Dreadnought,Free Dac Volunteers Engineering Corps,NaN,1088.00,950.0,600.0,0.0,15000000.0,6 years,1.50,60.0,Dreadnought,General Grievous,Revenge of the Sith
56,57,Malevolence,Subjugator-class heavy cruiser,Free Dac Volunteers Engineering Corps,NaN,4845.00,975.0,216.0,0.0,14000000.0,6 years,1.50,60.0,Heavy cruiser,General Grievous,The Clone Wars
57,58,Invisible Hand,Providence-class Dreadnought,Free Dac Volunteers Engineering Corps,NaN,1088.00,950.0,600.0,0.0,15000000.0,6 years,1.50,60.0,Dreadnought,General Grievous,Revenge of the Sith
58,59,Droid Control Ship,Lucrehulk-class battleship,Hoersch-Kessel Drive,NaN,3170.00,950.0,150.0,0.0,55000000.0,6 years,2.00,60.0,Battleship,None,The Phantom Menace
59,60,Venator-class Star Destroyer,Venator-class,Kuat Drive Yards,NaN,1137.00,975.0,7400.0,2000.0,20000000.0,6 years,2.00,60.0,Capital ship,None,"Revenge of the Sith, The Clone Wars"

In [7]:
parquet_path1 = "C:\\Users\\sriharini\\Documents\\weapons.parquet"

In [37]:
df_parquet1 = pd.read_parquet(parquet_path1, engine="pyarrow")

In [38]:
df_parquet1

,id,name,model,manufacturer,cost_in_credits,length,type,description,films
0,1,Lightsaber,Standard Lightsaber,Various,NaN,1.00,Melee,A weapon with a plasma blade powered by a kybe...,All Episodes
1,2,DL-44 Blaster Pistol,DL-44,BlasTech Industries,1500.0,0.30,Blaster,A powerful and highly modifiable blaster pistol.,"A New Hope, The Empire Strikes Back, Return of..."
2,3,E-11 Blaster Rifle,E-11,BlasTech Industries,1000.0,0.43,Blaster,Standard issue blaster rifle for Imperial stor...,"A New Hope, The Empire Strikes Back, Return of..."
3,4,Bowcaster,Wookiee Bowcaster,Various,NaN,1.50,Projectile,A traditional Wookiee weapon that fires explos...,"A New Hope, The Force Awakens, The Last Jedi"
4,5,Thermal Detonator,Model TD,Various,2000.0,0.10,Explosive,A highly destructive grenade.,"Return of the Jedi, The Force Awakens"
5,6,Electrostaff,Z6 Riot Control Baton,Merr-Sonn Munitions,NaN,2.00,Melee,"A staff that delivers electric shocks, used by...",The Force Awakens
6,7,DC-15A Blaster Rifle,DC-15A,BlasTech Industries,2500.0,1.26,Blaster,A heavy blaster rifle used by clone troopers.,"Attack of the Clones, Revenge of the Sith"
7,8,Force Pike,Force Pike,Various,NaN,2.00,Melee,A staff weapon used by the Emperor's Royal Guard.,Return of the Jedi
8,9,SE-14C Blaster Pistol,SE-14C,BlasTech Industries,800.0,0.22,Blaster,A rapid-fire blaster pistol.,A New Hope
9,10,Westar-34 Blaster,Westar-34,BlasTech Industries,1200.0,0.23,Blaster,A pair of blaster pistols used by Jango Fett.,Attack of the Clones
10,11,DH-17 Blaster Pistol,DH-17,BlasTech Industries,1200.0,0.30,Blaster,A blaster pistol used by the Rebel Alliance.,"A New Hope, The Empire Strikes Back"
11,12,DC-17 Hand Blaster,DC-17,BlasTech Industries,1500.0,0.32,Blaster,A blaster pistol used by clone troopers.,The Clone Wars
12,13,A280 Blaster Rifle,A280,BlasTech Industries,2000.0,0.45,Blaster,A heavy blaster rifle used by the Rebel Alliance.,Return of the Jedi
13,14,RT-97C Heavy Blaster Rifle,RT-97C,BlasTech Industries,3000.0,1.20,Blaster,A heavy blaster rifle used by Imperial stormtr...,A New Hope
14,15,F-11D Blaster Rifle,F-11D,Sonn-Blas Corporation,2500.0,1.10,Blaster,A blaster rifle used by the First Order stormt...,"The Force Awakens, The Last Jedi, The Rise of ..."
15,16,Sonic Rifle,ZX Miniature Proton Rifle,Baktoid Armor Workshop,3500.0,1.40,Blaster,A sonic rifle used by the Geonosians.,Attack of the Clones
16,17,Ryyk Blade,Ryyk Blade,Wookiees,NaN,1.00,Melee,A traditional Wookiee melee weapon.,Star Wars: The Clone Wars
17,18,Z-6 Rotary Blaster Cannon,Z-6,BlasTech Industries,5000.0,1.50,Blaster,A rotary blaster cannon used by clone troopers.,The Clone Wars
18,19,Gaderffii,Gaderffii,Tusken Raiders,NaN,1.50,Melee,A traditional melee weapon used by the Tusken ...,"A New Hope, Attack of the Clones"
19,20,Bo-Rifle,Bo-Rifle,Lasat,NaN,2.00,Melee/Blaster,A hybrid melee and blaster weapon used by the ...,Star Wars Rebels
20,21,DLT-19 Heavy Blaster Rifle,DLT-19,BlasTech Industries,4500.0,1.10,Blaster,A heavy blaster rifle used by Imperial stormtr...,A New Hope
21,22,Kyuzo Petar,Kyuzo Petar,Kyuzo,NaN,1.20,Melee,A traditional melee weapon used by the Kyuzo.,The Clone Wars
22,23,Electro-proton Bomb,Electro-proton Bomb,Galactic Republic,NaN,NaN,Explosive,A massive bomb used to disable droids.,The Clone Wars
23,24,Nightsister Energy Bow,Energy Bow,Nightsisters,NaN,1.50,Projectile,A traditional bow used by the Nightsisters.,The Clone Wars
24,25,Relby-v10 Mortar Gun,Relby-v10,BlasTech Industries,5000.0,1.20,Blaster,A mortar gun used by bounty hunters.,Star Wars Rebels
25,26,Stun Baton,Stun Baton,First Order,NaN,0.80,Melee,A melee weapon used by the First Order stormtr...,The Force Awakens
26,27,Particle Beam Blaster,Particle Beam Blaster,Various,3000.0,0.40,Blaster,A blaster that fires particle beams.,The Clone Wars
27,28,Vibroblade,Vibroblade,Various,NaN,0.50,Melee,A melee weapon with a vibrating blade.,"The Clone Wars, The Mandalorian"
28,29,DC-15S Blaster Carbine,DC-15S,BlasTech Industries,1500.0,0.76,Blaster,A compact blaster carbine used by clone troopers.,"Attack of the Clones, Revenge of the Sith"
29,30,Whipcord Thrower,Whipcord Thrower,Various,NaN,NaN,Projectile,A wrist-mounted device that fires a whipcord.,The Mandalorian
30,31,Wrist Rocket,Wrist Rocket,Various,NaN,NaN,Projectile,A wrist-mounted rocket launcher.,The Mandalorian
31,32,Flame Thrower,Flame Thrower,Various,NaN,NaN,Projectile,A device that projects a stream of fire.,The Mandalorian
32,33,Amban Phase-Pulse Blaster,Amban,Various,NaN,1.50,Blaster,A blaster with a long barrel used by the Manda...,The Mandalorian
33,34,Vibro-ax,Vibro-ax,Various,NaN,1.20,Melee,A melee weapon with a vibrating blade.,Return of the Jedi
34,35,Power Hammer,Power Hammer,Various,NaN,1.00,Melee,A hammer with an energy source to increase its...,Star Wars: The Clone Wars
35,36,Ion Blaster,Ion Blaster,Various,1800.0,0.50,Blaster,A blaster that fires ion energy to disable ele...,The Clone Wars
36,37,Stun Gun,Stun Gun,Various,1200.0,0.30,Blaster,A weapon that emits a stunning energy beam.,The Mandalorian
37,38,Proton Torpedo,Proton Torpedo,Various,NaN,NaN,Projectile,A powerful torpedo used in space battles.,"A New Hope, The Empire Strikes Back, Return of..."
38,39,Bow Rifle,Bow Rifle,Lasat,NaN,1.50,Melee/Blaster,A hybrid melee and blaster weapon used by the ...,Star Wars Rebels
39,40,Force Lance,Force Lance,Jedi,NaN,1.20,Melee,A melee weapon imbued with the Force.,Star Wars: The Clone Wars
40,41,DC-17m Interchangeable Weapon System,DC-17m,BlasTech Industries,3500.0,0.85,Blaster,A modular blaster used by clone commandos.,Star Wars: Republic Commando
41,42,Geonosian Sonic Blaster,Sonic Blaster,Baktoid Armor Workshop,2500.0,1.00,Blaster,A blaster that fires sonic energy.,Attack of the Clones
42,43,E-Web Heavy Blaster,E-Web,BlasTech Industries,5000.0,2.00,Blaster,A heavy blaster used by Imperial forces.,"The Empire Strikes Back, The Mandalorian"
43,44,Vibrosword,Vibrosword,Various,NaN,1.20,Melee,A sword with a vibrating blade.,The Clone Wars
44,45,T-7 Ion Disruptor Rifle,T-7,SoroSuub Corporation,4000.0,1.10,Blaster,An ion disruptor rifle used by the Empire.,Star Wars Rebels
45,46,Blurrg-1120 Holdout Blaster,Blurrg-1120,BlasTech Industries,1200.0,0.20,Blaster,A compact blaster pistol used by the Resistance.,The Last Jedi
46,47,Scatterblaster,Scatterblaster,Various,2000.0,0.60,Blaster,A blaster that fires in a wide spread.,Star Wars: Battlefront
47,48,Stokhli Spray Stick,Spray Stick,Various,NaN,1.50,Blaster,A weapon that fires a stream of immobilizing s...,Star Wars: Galaxy's Edge
48,49,Bowcaster,Wookiee Bowcaster,Various,NaN,1.50,Projectile,A traditional Wookiee weapon that fires explos...,"A New Hope, The Force Awakens, The Last Jedi"
49,50,Disruptor Rifle,Disruptor Rifle,Various,4500.0,1.00,Blaster,A blaster that disintegrates its target.,The Mandalorian
50,51,Thermal Detonator,Model TD,Various,2000.0,0.10,Explosive,A highly destructive grenade.,"Return of the Jedi, The Force Awakens"
51,52,Bo-Rifle,Bo-Rifle,Lasat,NaN,2.00,Melee/Blaster,A hybrid melee and blaster weapon used by the ...,Star Wars Rebels
52,53,DL-18 Blaster Pistol,DL-18,BlasTech Industries,1500.0,0.35,Blaster,A common blaster pistol.,Return of the Jedi
53,54,C1 Personal Ion Blaster,C1,Various,2000.0,0.40,Blaster,An ion blaster used by bounty hunters.,The Clone Wars
54,55,Relby-k23 Blaster Pistol,Relby-k23,BlasTech Industries,1200.0,0.25,Blaster,A blaster pistol used by bounty hunters.,The Clone Wars
55,56,KX-80 Repeating Blaster,KX-80,BlasTech Industries,5000.0,1.50,Blaster,A heavy repeating blaster.,The Clone Wars
56,57,Disruptor Pistol,Disruptor Pistol,Various,3000.0,0.30,Blaster,A disruptor pistol that disintegrates its target.,The Mandalorian
57,58,Dart Shooter,Dart Shooter,Various,NaN,0.20,Projectile,A wrist-mounted dart shooter.,The Mandalorian
58,59,Energy Sling,Energy Sling,Various,NaN,0.80,Projectile,A sling that fires energy projectiles.,Star Wars: The Clone Wars
59,60,Merr-Sonn Scatter Gun,Scatter Gun,Merr-Sonn Munitions,2200.0,0.80,Blaster,A scatter gun that fires a wide spread of blas...,The Force Awakens

In [8]:
parquet_path2 = "C:\\Users\\sriharini\\Documents\\characters.parquet"

In [40]:
df_parquet2 = pd.read_parquet(parquet_path2, engine="pyarrow")

In [41]:
df_parquet

,id,name,model,manufacturer,cost_in_credits,length,max_atmosphering_speed,crew,passengers,cargo_capacity,consumables,hyperdrive_rating,MGLT,starship_class,pilots,films
0,1,Millennium Falcon,YT-1300 light freighter,Corellian Engineering Corporation,1.000000e+05,34.75,1050.0,4.0,6.0,100000.0,2 months,0.50,75.0,Light freighter,"Han Solo, Chewbacca","A New Hope, The Empire Strikes Back, Return of..."
1,2,X-wing,T-65 X-wing starfighter,Incom Corporation,1.499990e+05,12.50,1050.0,1.0,0.0,110.0,1 week,1.00,100.0,Starfighter,Luke Skywalker,"A New Hope, The Empire Strikes Back, Return of..."
2,3,TIE Fighter,Twin Ion Engine/Ln Starfighter,Sienar Fleet Systems,7.500000e+04,8.99,1200.0,1.0,0.0,65.0,2 days,1.00,100.0,Starfighter,None,"A New Hope, The Empire Strikes Back, Return of..."
3,4,Star Destroyer,Imperial I-class Star Destroyer,Kuat Drive Yards,1.500000e+08,1600.00,975.0,47060.0,0.0,36000000.0,2 years,2.00,60.0,Capital ship,None,"A New Hope, The Empire Strikes Back, Return of..."
4,5,Slave 1,Firespray-31-class patrol and attack craft,Kuat Systems Engineering,NaN,21.50,1000.0,1.0,6.0,80000.0,1 month,3.00,70.0,Patrol craft,Boba Fett,"The Empire Strikes Back, Attack of the Clones,..."
5,6,A-wing,RZ-1 A-wing interceptor,Alliance Underground Engineering,1.750000e+05,9.60,1300.0,1.0,0.0,40.0,1 week,1.00,120.0,Interceptor,None,"Return of the Jedi, The Last Jedi"
6,7,B-wing,A/SF-01 B-wing starfighter,Slayn & Korpil,2.200000e+05,16.90,950.0,1.0,0.0,45.0,1 week,2.00,91.0,Assault starfighter,None,Return of the Jedi
7,8,Y-wing,BTL Y-wing starfighter,Koensayr Manufacturing,1.350000e+05,23.40,1000.0,2.0,0.0,110.0,1 week,1.00,80.0,Assault starfighter,None,"A New Hope, The Empire Strikes Back, Return of..."
8,9,Executor,Executor-class Star Dreadnought,"Kuat Drive Yards, Fondor Shipyards",1.143350e+09,19000.00,975.0,279144.0,38000.0,250000000.0,6 years,4.00,40.0,Star Dreadnought,Darth Vader,"The Empire Strikes Back, Return of the Jedi"
9,10,Rebel transport,GR-75 medium transport,"Gallofree Yards, Inc.",3.000000e+06,90.00,650.0,6.0,90.0,19000000.0,6 months,4.00,20.0,Medium transport,None,"The Empire Strikes Back, Return of the Jedi"
10,11,Naboo Royal Starship,J-type 327 Nubian,Theed Palace Space Vessel Engineering Corps,NaN,76.00,920.0,8.0,20.0,2000000.0,1 month,1.80,75.0,Yacht,Queen Amidala,The Phantom Menace
11,12,ARC-170,Aggressive ReConnaissance-170 starfighter,"Incom Corporation, Subpro Corporation",NaN,14.50,1000.0,3.0,0.0,110.0,5 days,1.00,100.0,Starfighter,None,Revenge of the Sith
12,13,Eta-2 Actis,Eta-2 Actis-class light interceptor,Kuat Systems Engineering,NaN,5.47,1500.0,1.0,0.0,60.0,2 days,1.00,85.0,Interceptor,"Anakin Skywalker, Obi-Wan Kenobi",Revenge of the Sith
13,14,Venator-class Star Destroyer,Venator-class,Kuat Drive Yards,NaN,1137.00,975.0,7400.0,2000.0,20000000.0,6 years,2.00,60.0,Capital ship,None,"Revenge of the Sith, The Clone Wars"
14,15,Naboo N-1 Starfighter,N-1,Theed Palace Space Vessel Engineering Corps,NaN,11.00,1100.0,1.0,0.0,65.0,3 days,1.00,100.0,Starfighter,Anakin Skywalker,"The Phantom Menace, Attack of the Clones"
15,16,Jedi Interceptor,Eta-2 Actis-class interceptor,Kuat Systems Engineering,NaN,5.47,1500.0,1.0,0.0,60.0,2 days,1.00,85.0,Interceptor,"Anakin Skywalker, Obi-Wan Kenobi",Revenge of the Sith
16,17,Sith Infiltrator,Scimitar,Republic Sienar Systems,NaN,26.50,1180.0,1.0,6.0,150000.0,1 month,1.50,80.0,Starfighter,Darth Maul,The Phantom Menace
17,18,V-wing,Alpha-3 Nimbus-class V-wing starfighter,Kuat Systems Engineering,NaN,7.90,1050.0,1.0,0.0,60.0,2 days,1.00,90.0,Starfighter,None,Revenge of the Sith
18,19,Delta-7 Aethersprite,Delta-7 Aethersprite-class light interceptor,Kuat Systems Engineering,NaN,8.00,1150.0,1.0,0.0,60.0,2 days,1.00,90.0,Interceptor,Obi-Wan Kenobi,Attack of the Clones
19,20,Imperial Shuttle,Lambda-class T-4a shuttle,Sienar Fleet Systems,NaN,20.00,850.0,6.0,20.0,80000.0,1 month,1.00,50.0,Shuttle,Emperor Palpatine,Return of the Jedi
20,21,Tantive IV,CR90 corvette,Corellian Engineering Corporation,3.500000e+06,150.00,950.0,165.0,30.0,3000000.0,1 year,2.00,60.0,Corvette,Leia Organa,"A New Hope, Revenge of the Sith"
21,22,Slave II,Firespray-31-class patrol and attack craft,Kuat Systems Engineering,NaN,21.50,1000.0,1.0,6.0,80000.0,1 month,3.00,70.0,Patrol craft,Boba Fett,"The Empire Strikes Back, Attack of the Clones,..."
22,23,TIE Bomber,TIE/sa bomber,Sienar Fleet Systems,NaN,7.80,850.0,1.0,0.0,40.0,2 days,1.00,60.0,Bomber,None,The Empire Strikes Back
23,24,Imperial Star Destroyer,Imperial I-class Star Destroyer,Kuat Drive Yards,1.500000e+08,1600.00,975.0,47060.0,0.0,36000000.0,2 years,2.00,60.0,Capital ship,None,"A New Hope, The Empire Strikes Back, Return of..."
24,25,Sith Speeder,FC-20 speeder bike,Razalon,NaN,2.00,180.0,1.0,0.0,10.0,1 day,NaN,NaN,Speeder,Darth Maul,The Phantom Menace
25,26,Speeder Bike,74-Z speeder bike,Aratech Repulsor Company,NaN,3.00,360.0,1.0,1.0,4.0,2 days,NaN,NaN,Speeder,None,Return of the Jedi
26,27,Solar Sailer,Punworcca 116-class interstellar sloop,Huppla Pasa Tisc Shipwrights Collective,NaN,15.20,NaN,3.0,11.0,180000.0,1 month,1.50,60.0,Sloop,Count Dooku,Attack of the Clones
27,28,Geonosian Starfighter,Nantex-class territorial defense starfighter,Huppla Pasa Tisc Shipwrights Collective,NaN,9.80,1200.0,1.0,0.0,30.0,2 days,1.00,100.0,Starfighter,None,Attack of the Clones
28,29,Hound's Tooth,YT-2000 light freighter,Corellian Engineering Corporation,NaN,20.00,850.0,6.0,10.0,500000.0,2 months,1.00,75.0,Light freighter,Bossk,The Clone Wars
29,30,Scimitar,Sith Infiltrator,Republic Sienar Systems,NaN,26.50,1180.0,1.0,6.0,150000.0,1 month,1.50,80.0,Starfighter,Darth Maul,The Phantom Menace
30,31,Tie Interceptor,TIE/in interceptor,Sienar Fleet Systems,NaN,9.60,1250.0,1.0,0.0,75.0,2 days,1.00,110.0,Starfighter,None,Return of the Jedi
31,32,Naboo Royal Cruiser,J-type diplomatic barge,Theed Palace Space Vessel Engineering Corps,NaN,115.00,920.0,8.0,50.0,500000.0,2 months,1.80,75.0,Yacht,Queen Amidala,Attack of the Clones
32,33,X-34 Landspeeder,X-34,SoroSuub Corporation,NaN,3.40,250.0,1.0,1.0,5.0,2 days,NaN,NaN,Landspeeder,Luke Skywalker,A New Hope
33,34,Snowspeeder,T-47 airspeeder,Incom Corporation,NaN,5.30,650.0,2.0,0.0,10.0,2 days,NaN,NaN,Airspeeder,Luke Skywalker,The Empire Strikes Back
34,35,The Ghost,VCX-100 light freighter,Corellian Engineering Corporation,NaN,43.90,1025.0,4.0,6.0,70000.0,2 months,1.00,70.0,Light freighter,Hera Syndulla,Star Wars Rebels
35,36,Phantom,VCX-series auxiliary starfighter,Corellian Engineering Corporation,NaN,14.10,1050.0,1.0,6.0,40000.0,1 month,1.00,90.0,Auxiliary starfighter,Ezra Bridger,Star Wars Rebels
36,37,Outrider,YT-2400 light freighter,Corellian Engineering Corporation,NaN,21.50,950.0,2.0,6.0,70000.0,2 months,0.75,70.0,Light freighter,Dash Rendar,Shadows of the Empire
37,38,Razor Crest,ST-70 Assault Ship,Kuat Drive Yards,NaN,24.00,1000.0,2.0,6.0,50000.0,1 month,1.00,75.0,Assault ship,Din Djarin,The Mandalorian
38,39,Naboo Yacht,J-type star skiff,Theed Palace Space Vessel Engineering Corps,NaN,29.20,920.0,8.0,30.0,300000.0,1 month,1.80,75.0,Yacht,Padmé Amidala,Revenge of the Sith
39,40,U-wing,UT-60D,Incom Corporation,NaN,24.20,950.0,4.0,8.0,40000.0,1 month,1.00,80.0,Transport,Cassian Andor,Rogue One
40,41,TIE Advanced x1,TIE Advanced x1,Sienar Fleet Systems,NaN,9.20,1200.0,1.0,0.0,75.0,2 days,1.00,105.0,Starfighter,Darth Vader,A New Hope
41,42,J-type 327 Nubian,J-type 327,Theed Palace Space Vessel Engineering Corps,NaN,76.00,920.0,8.0,20.0,2000000.0,1 month,1.80,75.0,Yacht,Queen Amidala,The Phantom Menace
42,43,Naboo Royal Starship,J-type 327 Nubian,Theed Palace Space Vessel Engineering Corps,NaN,76.00,920.0,8.0,20.0,2000000.0,1 month,1.80,75.0,Yacht,Queen Amidala,The Phantom Menace
43,44,Naboo N-1 Starfighter,N-1,Theed Palace Space Vessel Engineering Corps,NaN,11.00,1100.0,1.0,0.0,65.0,3 days,1.00,100.0,Starfighter,Anakin Skywalker,"The Phantom Menace, Attack of the Clones"
44,45,Sith Infiltrator,Scimitar,Republic Sienar Systems,NaN,26.50,1180.0,1.0,6.0,150000.0,1 month,1.50,80.0,Starfighter,Darth Maul,The Phantom Menace
45,46,Havoc Marauder,Omicron-class attack shuttle,Cygnus Spaceworks,NaN,22.30,1050.0,2.0,12.0,70000.0,1 month,1.00,70.0,Attack shuttle,Clone Force 99,The Bad Batch
46,47,Luthen's Ship,Fondor Haulcraft,Fondor Shipyards,NaN,34.80,1000.0,1.0,6.0,100000.0,1 month,1.00,80.0,Haulcraft,Luthen Rael,Andor
47,48,Tantive IV,CR90 corvette,Corellian Engineering Corporation,3.500000e+06,150.00,950.0,165.0,30.0,3000000.0,1 year,2.00,60.0,Corvette,Leia Organa,"A New Hope, Revenge of the Sith"
48,49,Millennium Falcon,YT-1300 light freighter,Corellian Engineering Corporation,1.000000e+05,34.75,1050.0,4.0,6.0,100000.0,2 months,0.50,75.0,Light freighter,"Han Solo, Chewbacca","A New Hope, The Empire Strikes Back, Return of..."
49,50,Jedi Starfighter,Delta-7 Aethersprite-class light interceptor,Kuat Systems Engineering,NaN,8.00,1150.0,1.0,0.0,60.0,2 days,1.00,90.0,Interceptor,Obi-Wan Kenobi,Attack of the Clones
50,51,Vulture Droid,Variable Geometry Self-Propelled Battle Droid,Haor Chall Engineering,NaN,3.50,1200.0,NaN,NaN,NaN,NaN,1.00,100.0,Starfighter,None,The Phantom Menace
51,52,Tri-Fighter,Droid Tri-Fighter,"Colla Designs, Phlac-Arphocc Automata Industries",NaN,5.40,1180.0,NaN,NaN,NaN,NaN,1.00,100.0,Starfighter,None,Revenge of the Sith
52,53,Hyena Bomber,Baktoid Armor Workshop,"Colla Designs, Phlac-Arphocc Automata Industries",NaN,14.90,1180.0,NaN,NaN,NaN,NaN,1.00,100.0,Starfighter,None,The Clone Wars
53,54,Droid Gunship,Heavy Missile Platform,Baktoid Fleet Ordnance,NaN,12.00,950.0,NaN,NaN,NaN,NaN,1.00,100.0,Gunship,None,The Clone Wars
54,55,Malevolence,Subjugator-class heavy cruiser,Free Dac Volunteers Engineering Corps,NaN,4845.00,975.0,216.0,0.0,14000000.0,6 years,1.50,60.0,Heavy cruiser,General Grievous,The Clone Wars
55,56,Invisible Hand,Providence-class Dreadnought,Free Dac Volunteers Engineering Corps,NaN,1088.00,950.0,600.0,0.0,15000000.0,6 years,1.50,60.0,Dreadnought,General Grievous,Revenge of the Sith
56,57,Malevolence,Subjugator-class heavy cruiser,Free Dac Volunteers Engineering Corps,NaN,4845.00,975.0,216.0,0.0,14000000.0,6 years,1.50,60.0,Heavy cruiser,General Grievous,The Clone Wars
57,58,Invisible Hand,Providence-class Dreadnought,Free Dac Volunteers Engineering Corps,NaN,1088.00,950.0,600.0,0.0,15000000.0,6 years,1.50,60.0,Dreadnought,General Grievous,Revenge of the Sith
58,59,Droid Control Ship,Lucrehulk-class battleship,Hoersch-Kessel Drive,NaN,3170.00,950.0,150.0,0.0,55000000.0,6 years,2.00,60.0,Battleship,None,The Phantom Menace
59,60,Venator-class Star Destroyer,Venator-class,Kuat Drive Yards,NaN,1137.00,975.0,7400.0,2000.0,20000000.0,6 years,2.00,60.0,Capital ship,None,"Revenge of the Sith, The Clone Wars"